# Generated by Django 4.2.6 on 2023-10-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('pid', models.IntegerField()),
                ('pname', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('sid', models.IntegerField()),
            ],
        ),
    ]
