# Generated by Django 4.2.6 on 2023-10-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_rename_image_shop_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='ct',
            field=models.TimeField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='shop',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='ot',
            field=models.TimeField(default='', max_length=10),
        ),
    ]
